### PR TITLE
Container improvements

### LINKED ISSUE #338: Expose static methods from component classes wrapped in containers
I've got a component which uses the willTransitionTo static method from react-router. Wrapping this component in a Marty container seems to stop this from being called. I've had a look through the Marty source and it looks like, in the process of cloning the component to return the new one that listens to the stores etc, willTransitionTo is being stripped out so doesn't actually exist in the new component returned from createContainer. Is this right or is something else happening?

Original issue posted on: https://gitter.im/martyjs/marty - June 8 2015

### PR DESCRIPTION
**Pull request by taion**
~~Fixes martyjs/marty#338~~

EDIT: I'm going to put the fixes for martyjs/marty#338 and #17 here to avoid creating extra merge resolution issues. They're somewhat related, so I don't think this is unreasonable.

### CODE REVIEW

**Comment by taion** [comment]
I don't understand the test failures here - they're all of the form "could not start", it seems.

**Comment by taion** [comment]
It seemed cleaner to put `injectApp` in `createContainer.js` because both it and `createContainer` need the same `DEFAULT_CONTEXT_TYPES`. I can move it out if that seems better.

**Comment by jhollingworth** [comment]
lgtm :+1:

**Comment by jhollingworth** [comment]
Thanks for this PR :smile:

**Pull request merged**
